### PR TITLE
refs #23: Add collapse button for sidebar

### PR DESCRIPTION
**Pull request by Niremizov**
Very fast solution (ugly), probably someone would have better ideas how to make this changes cleaner.

### CODE REVIEW

**Comment by undigo** [comment]
I try to replace the original theme with this for add collapse button for sidebar but no evolution :
image 903

**Comment by theblackhole** [comment]
@undigo see PR #26 Until it's merged, you can use my fork : https://github.com/theblackhole/minelab/tree/fix-menu-children

**Comment by jonian** [comment]
Hi @Niremizov. Thank you for your pull request. Can you move styles to the css files, so I can accept this?

EX:

<div id="hideSidebarButton" style="position:absolute; z-index: 20; top: 2px; cursor: pointer;">

**Comment by Niremizov** [comment]
Ok. ill try.

**Comment by undigo** [comment]
@theblackhole when I go to https://github.com/theblackhole/minelab/tree/fix-menu-children I've got an 404 error page
which branch to use ?

**Comment by jonian** [comment]
@undigo. PR #26 is merged, you can use the master baranch of this repo.

**Comment by jonian** [comment]
I'm merging this, add I will move inline css to sass files

**Pull request merged**
