### PR TITLE
include feature - Drag'n'drop order configuration for statuses, trackers, roles

### PR DESCRIPTION
**Pull request by pkestefran**
Hello,
please review this request and possibly merge. Thank you.
It is related to [Issue 40](https://github.com/hardpixel/minelab/issues/40)

The end result should look like this:
2016-10-25_10h52_02

### CODE REVIEW

**Comment by goutnet** [comment]
Will give it a go later this week (hopefuly today) thanks

**Comment by goutnet** [comment]
Hum … it seems that last update is not related to the initial pull request… can you describe it with a screenshot please?

**Comment by pkestefran** [comment]
Hi, my bad, the last commit is not related to the pull request. Is it possible to merge only the first two ?
Thanks.

**Comment by goutnet** [comment]
Well I could cherrypick your commits, but that would require some work, and also it would be against all good practices.

At this point you have several solutions:

1. Document your changes by adding a new screenshot so we can know what you are trying to fix
2. Revert the last commit 
3. Close the pull request and open 2 different requests

I suggest nb 1, since it does not seem to be a huge one, and I'll let it slip. (it would be a different story if it was a huge commit with tons of features, but small mistakes happens :) ).

So, can you simply describe what you tried to achieve on that last commit?

**Comment by pkestefran** [comment]
Hi, thanks for quick tips on the solutions. 
The last commit was reverted. That was just some playing around that I have committed to master. I'm quite new to using github, next time Ill create a branch for anything :)

**Comment by goutnet** [comment]
checking now

**Comment by goutnet** [comment]
Very nice indeed! merging now :)

**Pull request merged**
